// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Url struct {
	ID              string
	LongUrl         sql.NullString
	ShortenedUrlKey sql.NullString
}
